### ISSUE TITLE
Error when submitting contact form

### ISSUE THREAD

**Issue by wbnns** [blockchaincr/blockchaincr.com#2]
Reference:

![image](https://user-images.githubusercontent.com/1130872/29904244-1af1de24-8dc5-11e7-80f6-9d434a8b6880.png)

Submitting an inquiry through the contact form results in a redirect to formspree.io and displays a 405 Error:

![image](https://user-images.githubusercontent.com/1130872/29904307-69acbdcc-8dc5-11e7-8563-f97415bdbcc5.png)

**Comment by gaboesquivel** [comment]
This should be fixed
