### ISSUE TITLE
Unable to see text being typed into mailing list sign up

### ISSUE THREAD

**Issue by wbnns** [blockchaincr/blockchaincr.com#3]
Reference:

![screen recording 2017-08-30 at 20 59](https://user-images.githubusercontent.com/1130872/29904470-30279aa8-8dc6-11e7-8c26-86a179ddd502.gif)

It seems the font color for the input text on the mailing list subscription form may be the same color as the background.

**Comment by gaboesquivel** [comment]
This should be fixed now, let me know if it is specific browser thing
