### ISSUE TITLE
Contact email address maybe needs to be updated in opt-in email for mailing list

### ISSUE THREAD

**Issue by wbnns** [blockchaincr/blockchaincr.com#4]
Reference:

![image](https://user-images.githubusercontent.com/1130872/29904621-ed1cdcd6-8dc6-11e7-9bfc-969cc75f91f9.png)

@gaboesquivel Not sure if you want to change your email address to an @blockchaincr.com email address, so mentioning here in case you do.

**Comment by gaboesquivel** [comment]
thanks good catch
